### ISSUE TITLE
Bower compatibility - issues

### ISSUE THREAD

**Issue by MarkAPhillips** [makinacorpus/Leaflet.Spin#11]
Hi - would it possible to update the versions of leaflet and spin versions used as dependencies - i get the following when running

```
bower list
```

```
leaflet-spin#0.1.0
│ ├── leaflet#0.7.3 incompatible with ^0.6.1 (0.6.4 available, latest is 0.7.3)
│ └── spin.js#1.3.3 (latest is 2.3.1)
```

Thanks

**Comment by MarkAPhillips** [comment]
This needs updating in the bower devDependency section

```
"dependencies": {
    "leaflet": "^0.6.1",
    "spin.js": "^1.2.8"
  },
```

to 

```
"dependencies": {
    "leaflet": "^0.7.3",
    "spin.js": "^2.3.1"
  },
```

Can I suggest this is done and tested - I can look at it if you wish at some point to see if there are any breaking changes - thanks

**Comment by fredericbonifas** [comment]
I just updated the leaflet and spin.js versions and tested it. Please tell me if you have any problem

**Comment by MarkAPhillips** [comment]
Hi - thanks but the spin.js version is incorrect. The latest version is 2.3.1
Also would it be possible to create a new release v0.1.1 (also bower.json would need updating)

```
{
  "name": "leaflet-spin",
  "version": "0.1.1",
...
```

with these changes included.
once done - can pull it down and test - thanks

**Comment by fredericbonifas** [comment]
Should be fixed, my mistake :)

**Comment by MarkAPhillips** [comment]
Thanks will test and close if all works as expected

**Comment by MarkAPhillips** [comment]
OK does not seem to be an issues - if any arise will raise them
