### ISSUE TITLE
Wont work with require.js optimizer

### ISSUE THREAD

**Issue by Waowam** [makinacorpus/Leaflet.Spin#15]
Hi there,

I'm using leaflet.spin since a day or two and I spotted an error from require.js optimizer.

![From log](https://cloud.githubusercontent.com/assets/2901644/20423255/988a7120-ad6f-11e6-8a63-fa6137f0a9d8.png)

Its saying that there is more than one anonymous definition of module in leaflet.spin.js.
In fact there's a definition for each method your using to toggle the spinner. (SpinMapMixin, SpinMapInitHook).

I assume, as a state of art, each file that require.js optimizer want to normalize should have one and only one anonymous module definition or multiple definitions of non-anonymous modules.

If you mind, I can find some time to post a PR for you.
Atm I just commented one of the "define" to avoid the problem but we can do a lot better.

Regards,
Jérémy

**Comment by SBats** [comment]
Hi @Waowam  !

Thank you for reporting this issue.
I have made an attempt at cleaning the way we export the plugin and extend Leaflet both in commonjs and amd.

Could you try with the new version (1.1.0) and let me know if it works better ?

**Comment by mabhub** [comment]
As there's no response, I close this issue for now.  

Feel free to comment if there's anything new.
