### ISSUE TITLE
Can we show spinner while zooming?

### ISSUE THREAD

**Issue by jeevasusej** [makinacorpus/Leaflet.Spin#17]
Can we show spinner while zooming?

**Comment by leplatrem** [comment]
Yes, I think so, if Leaflet triggers the appropriate events :)

**Comment by SBats** [comment]
Yep, definitely!
You can use `zoomstart` and `zoomend` events of leaflet like this :
``` js
map.on('zoomstart', function () {
    map.spin(true);
} );
map.on('zoomend', function () {
    map.spin(false);
} );
```
