### ISSUE TITLE
Add bower.json

### ISSUE THREAD

**Issue by flibbertigibbet** [makinacorpus/Leaflet.Spin#8]
It would be great to be able to install this project using bower.

**Comment by jakehockey10** [comment]
:+1:

**Comment by fredericbonifas** [comment]
Do not hesitate to submit a pull request, we will be happy to review it :)

**Comment by jakehockey10** [comment]
I put my thumbs up because I'm just now starting to use bower and I don't think I would know how to make the changes that would allow people to install from bower. But if I learn that at some point and still want this, I'll give it a shot.

**Comment by fredericbonifas** [comment]
Thanks for your PR @flibbertigibbet !

Unfortunately, leaflet-spin has been registered 4 days ago on Bower with this fork: https://github.com/sebasrodriguez/Leaflet.Spin

@sebasrodriguez would you agree to unregister your bower package so I can register this repo under "leaflet-spin" ?

**Comment by sebasrodriguez** [comment]
@fredericbonifas Sure man. I'll do that right away. Please let me know once you register it back on bower.

**Comment by sebasrodriguez** [comment]
@fredericbonifas Done. It's all yours.

**Comment by MarkAPhillips** [comment]
Hi can this be registered with bower again as my build has a dependency and is failing as it is no longer available on bower - thanks

**Comment by fredericbonifas** [comment]
Thanks @sebasrodriguez !
@MarkAPhillips this should be registered on bower now, could you please confirm?

**Comment by MarkAPhillips** [comment]
Yes works as expected .. thanks

**Comment by MarkAPhillips** [comment]
Spoke too soon
Get the following error 
```
Additional error details:
[11:34:27][Step 3/7] Available versions: 0.1.0
[11:34:28][Step 3/7] Process exited with code 1
```

**Comment by sebasrodriguez** [comment]
@MarkAPhillips You should use the version that's on the makinacorpus/Leaflet.Spin repository bower.json, that would be 0.1.0 but on the other hand I would recommend @fredericbonifas to change the version in bower.json to 1.0.0 since is a stable version and it is production ready.

**Comment by MarkAPhillips** [comment]
Can this be closed now - thanks
